apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: automation-mgmt-eks
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "339337551661"
    provider: eks
    region: us-east-2
    registry: 339337551661.dkr.ecr.us-east-2.amazonaws.com
  environments:
  - key: dev
    owner: Morgan-and-Adam-will-figure-this-out
    repository: jx-asm-cluster-repo
  - key: staging
  - key: production
  ingress:
    domain: "kube.mymissing.link"
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jenkinsxbotmo
  repository: nexus
  secretStorage: secretsManager
  storage:
  - name: logs
    url: s3://logs-automation-mgmt-eks-20220809153643793100000007
  - name: reports
    url: s3://reports-automation-mgmt-eks-20220809153643792900000006
  - name: repository
    url: s3://repository-automation-mgmt-eks-20220809153643796600000008
  terraform: true
  vault: {}
  webhook: lighthouse
